//Icons

import store from "../../../redux/store";

const icon1 = <i className="bx bx-desktop"></i>;
const icon2 = <i className="ti ti-box"></i>;
const icon16 = <i className="bx bx-user"></i>;
const icon17 = <i className="ti ti-settings-automation"></i>;
const icon18 = <i className="ti ti-chart-infographic"></i>;
const icon3 = <i className="ti ti-settings"></i>;
const icon4 = <i className="bi bi-people"></i>;
const icon5 = <i className="bx bx-user-voice"></i>;
const icon6 = <i className="bx bx-user-circle"></i>;
const icon7 = <i className="ti ti-building-warehouse"></i>;
export const MENU_KEY = {
  DASHBOARD: "DASHBOARD",
  ACCOUNTS: "ACCOUNTS",

  CUSTOMERS: "CUSTOMERS",
  CUSTOMERS_VALIDATE: "CUSTOMERS_VALIDATE",
  CUSTOMERS_UNVALIDATE: "CUSTOMERS_UNVALIDATE",
  CUSTOMERS_SEARCH: "CUSTOMERS_SEARCH",

  EMPLOYEES: "EMPLOYEES",
  ROLES: "ROLES",
  DEPARTMENTS: "DEPARTMENTS",

  PRODUCTS: "PRODUCTS",
  PRODUCTS_INFO: "PRODUCTS_INFO",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  PRODUCTS_WAREHOUSE: "PRODUCTS_WAREHOUSE",
  PRODUCTS_SEARCH: "PRODUCTS_SEARCH",

  PROGRRAM_POINT: "PROGRAM_POINT",
  PROGRAM_TOPUP: "PROGRAM_TOPUP",
  PROGRAM_CHANCE: "PROGRAM_CHANCE",
  REPORT_CUSTOMER: "REPORT_CUSTOMER",
  REPORT_CHANCE: "REPORT_CHANCE",
  REPORT_IQR: "REPORT_IQR",
  REPORT_SMS: "REPORT_SMS",
  OPERATORS_SEARCH_PRODUCT: "OPERATORS_SEARCH_PRODUCT",
  OPERATORS_SEARCH_CUSTOMER: "OPERATORS_SEARCH_CUSTOMER",
  OPERATORS_SEARCH_CUSTOMER_TODAY: "OPERATORS_SEARCH_CUSTOMER_TODAY",
  OPERATORS_SEARCH_TOPUP_TODAY: "OPERATORS_SEARCH_TOPUP_TODAY",
  OPERATORS_SEARCH_CUSTOMER_VALIDATE_TODAY:
    "OPERATORS_SEARCH_CUSTOMER_VALIDATE_TODAY",
  OPERATORS_SEARCH_CUSTOMER_UNVALIDATE_TODAY:
    "OPERATORS_SEARCH_CUSTOMER_UNVALIDATE_TODAY",
  OPERATORS_CUSTOMER_SMS_6088: "OPERATORS_CUSTOMER_SMS_6088",
  SMS_GATEWAY: "SMS_GATEWAY",
  OPERATORS_LIST_ACHIEVE_TOPUP: "OPERATORS_LIST_ACHIEVE_TOPUP",
  REPORT_PROGRAM_POINT: "REPORT_PROGRAM_POINT",
  REPORT_PROGRAM_TOPUP: "REPORT_PROGRAM_TOPUP",

  SETTING_AREA: "SETTING_AREA",
  SETTING_GROUP_CUSTOMER: "SETTING_GROUP_CUSTOMER",
  SETTING_GROUP_RETAILER: "SETTING_GROUP_RETAILER",
  SETTING_BRAND: "SETTING_BRAND",
  SETTING_FORMULATION: "SETTING_FORMULATION",
  SETTING_INDICATION: "SETTING_INDICATION",

  MANAGE_PERSONEL: "MANGE_PERSONEL",
  MANAGE_PROGRAM: "MANGE_PROGRAM",
  MANAGE_REPORT: "MANGE_REPORT",
  MANAGE_SETTING: "MANGE_SETTING",
  MANAGE_OPERATOR: "MANGER_OPERATOR",
  MAIN_TITLE: "MAIN_TITLE",
  MANAGE_TITLE: "MANAGE_TITLE",
  REPORT_TITLE: "REPORT_TITLE",
  SETTING_TITLE: "SETTING_TITLE",
  MANAGE_WAREHOUSE: "MANAGE_WAREHOUSE",
  WARE_HOUSE_MANAGE_EXPORT: "WARE_HOUSE_MANAGE_EXPORT",
  WARE_HOUSE_MANAGE_IMPORT: "WARE_HOUSE_MANAGE_IMPORT",
  SEARCH_WAREHOUSE_EXPORT: "SEARCH_WAREHOUSE_EXPORT",
  SEARCH_WAREHOUSE_IMPORT: "SEARCH_WAREHOUSE_IMPORT",
  WAREHOUSES_INVENTORY_INFO: "WAREHOUSES_INVENTORY_INFO",
  WAREHOUSES_REPORT_EXPORT: "WAREHOUSES_REPORT_EXPORT",
};

export const MENUITEMS = [
  {
    menutitle: "MAIN",
    key: MENU_KEY.MAIN_TITLE,
  },
  {
    path: `${import.meta.env.BASE_URL}dashboards`,
    title: "Dashboard",
    icon: icon1,
    // badgetxt: badge1,
    type: "link",
    active: false,
    selected: false,
    key: MENU_KEY.DASHBOARD,
  },
  {
    menutitle: "Quản lý",
    key: MENU_KEY.MANAGE_TITLE,
  },
  {
    path: `${import.meta.env.BASE_URL}accounts`,
    title: "Tài khoản",
    icon: icon6,
    // badgetxt: badge1,
    type: "link",
    active: false,
    selected: false,
    key: MENU_KEY.ACCOUNTS,
  },
  {
    title: "Thông tin trong ngày",
    icon: icon5,
    badgetxt: "",
    type: "sub",
    active: true,
    selected: false,
    dirchange: false,
    key: MENU_KEY.MANAGE_OPERATOR,
    children: [
      // {
      //   path: `${import.meta.env.BASE_URL}operator/search-product-code`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false,
      //   title: "Tra cứu mã sản phẩm",
      //   key: MENU_KEY.OPERATORS_SEARCH_PRODUCT,
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}operator/search-customer`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false,
      //   title: "Tra cứu khách hàng",
      //   key: MENU_KEY.OPERATORS_SEARCH_CUSTOMER,
      // },
      {
        path: `${import.meta.env.BASE_URL}operator/search-customer-today`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "iQr",
        key: MENU_KEY.OPERATORS_SEARCH_CUSTOMER_TODAY,
      },
      {
        path: `${
          import.meta.env.BASE_URL
        }operator/search-customer-unvalidate-today`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Danh sách chờ xác thực",
        key: MENU_KEY.OPERATORS_SEARCH_CUSTOMER_UNVALIDATE_TODAY,
      },
      {
        path: `${
          import.meta.env.BASE_URL
        }operator/search-customer-validate-today`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Danh sách đã xác thực",
        key: MENU_KEY.OPERATORS_SEARCH_CUSTOMER_VALIDATE_TODAY,
      },
      {
        path: `${import.meta.env.BASE_URL}operator/search-topup-today`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Topup",
        key: MENU_KEY.OPERATORS_SEARCH_TOPUP_TODAY,
      },
      // {
      //   path: `${import.meta.env.BASE_URL}operator/customer-sms-6068`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false,
      //   title: "SMS 6088",
      //   key: MENU_KEY.OPERATORS_CUSTOMER_SMS_6088,
      // },
      {
        path: `${import.meta.env.BASE_URL}operator/topup/list`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Quà tặng",
        key: MENU_KEY.OPERATORS_LIST_ACHIEVE_TOPUP,
      },
      {
        path: `${import.meta.env.BASE_URL}operator/sms-gateway`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "SMS Gateway",
        key: MENU_KEY.SMS_GATEWAY,
      },
    ],
  },
  {
    title: "Thông tin kho",
    icon: icon7,
    badgetxt: "",
    type: "sub",
    active: true,
    selected: false,
    dirchange: false,
    key: MENU_KEY.MANAGE_WAREHOUSE,
    children: [
      {
        path: `${
          import.meta.env.BASE_URL
        }warehouse/export/search-warehouse-export`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Tra cứu xuất kho",
        key: MENU_KEY.SEARCH_WAREHOUSE_EXPORT,
      },

      {
        path: `${
          import.meta.env.BASE_URL
        }warehouse/import/search-warehouse-import`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Tra cứu nhập kho",
        key: MENU_KEY.SEARCH_WAREHOUSE_IMPORT,
      },
      {
        path: `${import.meta.env.BASE_URL}warehouse/export`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Danh sách xuất kho",
        key: MENU_KEY.WARE_HOUSE_MANAGE_EXPORT,
      },
      {
        path: `${import.meta.env.BASE_URL}warehouse/import`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Danh sách nhập kho",
        key: MENU_KEY.WARE_HOUSE_MANAGE_EXPORT,
      },
      {
        path: `${import.meta.env.BASE_URL}warehouse/report/export`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Báo cáo trong ngày",
        key: MENU_KEY.WAREHOUSES_REPORT_EXPORT,
      },
      {
        path: `${import.meta.env.BASE_URL}warehouse/inventory`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Danh sách tồn kho",
        key: MENU_KEY.WAREHOUSES_INVENTORY_INFO,
      },
    ],
  },
  {
    title: "Khách hàng",
    icon: icon4,
    badgetxt: "",
    type: "sub",
    active: true,
    selected: false,
    dirchange: false,
    key: MENU_KEY.CUSTOMERS,
    children: [
      {
        path: `${import.meta.env.BASE_URL}customer/search`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Tra cứu",
        key: MENU_KEY.CUSTOMERS_SEARCH,
      },
      {
        path: `${import.meta.env.BASE_URL}customer/validate`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Đã xác thực",
        key: MENU_KEY.CUSTOMERS_VALIDATE,
      },
      {
        path: `${import.meta.env.BASE_URL}customer/unvalidate`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Chờ xác thực",
        key: MENU_KEY.CUSTOMERS_UNVALIDATE,
      },
    ],
  },
  {
    title: "Nhân sự",
    icon: icon16,
    type: "sub",
    path: `${import.meta.env.BASE_URL}employee`,
    active: false,
    key: MENU_KEY.MANAGE_PERSONEL,
    children: [
      {
        path: `${import.meta.env.BASE_URL}employee`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Thông tin nhân sự",
        key: MENU_KEY.EMPLOYEES,
      },
      {
        path: `${import.meta.env.BASE_URL}employee/role`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Quản lý cấp bậc",
        key: MENU_KEY.ROLES,
      },
      {
        path: `${import.meta.env.BASE_URL}employee/department`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Quản lý bộ phận",
        key: MENU_KEY.DEPARTMENTS,
      },
    ],
  },
  {
    title: "Sản phẩm",
    type: "sub",
    active: false,
    selected: false,
    dirchange: false,
    icon: icon2,
    path: `${import.meta.env.BASE_URL}product`,
    key: MENU_KEY.PRODUCTS,
    children: [
      {
        path: `${import.meta.env.BASE_URL}product/search`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Tra cứu",
        key: MENU_KEY.PRODUCTS_SEARCH,
      },
      {
        path: `${import.meta.env.BASE_URL}product/info`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Thông tin Marketing",
        key: MENU_KEY.PRODUCTS_INFO,
      },
      {
        path: `${import.meta.env.BASE_URL}product/warehouse`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Thông tin Sản xuất",
        key: MENU_KEY.PRODUCTS_WAREHOUSE,
      },
    ],
  },
  {
    title: "Chương trình",
    icon: icon17,
    badgetxt: "",
    type: "sub",
    active: true,
    selected: false,
    dirchange: false,
    key: MENU_KEY.MANAGE_PROGRAM,

    children: [
      {
        path: `${import.meta.env.BASE_URL}program/point`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Tích điểm",
        key: MENU_KEY.PROGRRAM_POINT,
      },
      {
        path: `${import.meta.env.BASE_URL}program/topup`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Topup",
        key: MENU_KEY.PROGRAM_TOPUP,
      },
      {
        path: `${import.meta.env.BASE_URL}program/chance`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "May rủi",
        key: MENU_KEY.PROGRAM_CHANCE,
      },
    ],
  },
  {
    menutitle: "Báo cáo",
    key: MENU_KEY.REPORT_TITLE,
  },
  {
    path: `${import.meta.env.BASE_URL}report`,
    title: "Báo cáo",
    icon: icon18,
    type: "sub",
    active: false,
    selected: false,
    dirchange: false,
    key: MENU_KEY.MANAGE_REPORT,

    children: [
      {
        path: `${import.meta.env.BASE_URL}report/customer`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Khách hàng",
        key: MENU_KEY.REPORT_CUSTOMER,
      },
      {
        path: `${import.meta.env.BASE_URL}report/iQr`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "iQr",
        key: MENU_KEY.REPORT_IQR,
      },
      {
        path: `${import.meta.env.BASE_URL}report/program-point`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Chương trình tích điểm",
        key: MENU_KEY.PROGRRAM_POINT,
      },
      {
        path: `${import.meta.env.BASE_URL}report/topup`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Chương trình topup",
        key: MENU_KEY.PROGRAM_TOPUP,
      },
      {
        path: `${import.meta.env.BASE_URL}report/chance`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Chương trình may rủi",
        key: MENU_KEY.REPORT_CHANCE,
      },
      {
        path: `${import.meta.env.BASE_URL}report/sms`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "SMS",
        key: MENU_KEY.REPORT_SMS,
      },
    ],
  },
  {
    menutitle: "Cài đặt",
    key: MENU_KEY.SETTING_TITLE,
  },
  {
    title: "Cài đặt",
    type: "sub",
    active: false,
    selected: false,
    dirchange: false,
    icon: icon3,
    key: MENU_KEY.MANAGE_SETTING,

    children: [
      {
        path: `${import.meta.env.BASE_URL}setting/area`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Phân vùng",
        key: MENU_KEY.SETTING_AREA,
      },
      {
        path: `${import.meta.env.BASE_URL}setting/group-customer`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Nhóm khách hàng",
        key: MENU_KEY.SETTING_GROUP_CUSTOMER,
      },
      {
        path: `${import.meta.env.BASE_URL}setting/group-retailer`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Nhóm đại lý",
        key: MENU_KEY.SETTING_GROUP_RETAILER,
      },
      {
        path: `${import.meta.env.BASE_URL}setting/brand`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Nhãn hàng",
        key: MENU_KEY.SETTING_BRAND,
      },
      {
        path: `${import.meta.env.BASE_URL}setting/indication`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Nhóm thuốc",
        key: MENU_KEY.SETTING_INDICATION,
      },
      {
        path: `${import.meta.env.BASE_URL}setting/formulation`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Dạng thuốc",
        key: MENU_KEY.SETTING_FORMULATION,
      },
    ],
  },
];
