//Icons

import store from "../../../redux/store";

const icon1 = <i className="bx bx-desktop"></i>;
const icon2 = <i className="ti ti-box"></i>;
const icon16 = <i className="bx bx-user"></i>;
const icon17 = <i className="ti ti-settings-automation"></i>;
const icon18 = <i className="ti ti-chart-infographic"></i>;
const icon3 = <i className="ti ti-settings"></i>;
const icon4 = <i className="bi bi-people"></i>;
const icon5 = <i className="bx bx-user-voice"></i>;
const icon6 = <i className="bx bx-user-circle"></i>;
const icon7 = <i className="ti ti-building-warehouse"></i>;
export const MENU_KEY = {
  DASHBOARD: "DASHBOARD",
  ACCOUNTS: "ACCOUNTS",
  CUSTOMERS: "CUSTOMERS",
  EMPLOYEES: "EMPLOYEES",
  ROLES: "ROLES",
  DEPARTMENTS: "DEPARTMENTS",
  PRODUCTS: "PRODUCTS",
  PROGRRAM_POINT: "PROGRAM_POINT",
  PROGRAM_TOPUP: "PROGRAM_TOPUP",
  REPORT_AGENT: "REPORT_AGENT",
  REPORT_FARMER: "REPORT_FARMER",
  REPORT_IQR: "REPORT_IQR",
  REPORT_PROGRAM_POINT: "REPORT_PROGRAM_POINT",
  REPORT_PROGRAM_TOPUP: "REPORT_PROGRAM_TOPUP",
  SETTING_AREA: "SETTING_AREA",
  SETTING_GROUP_CUSTOMER: "SETTING_GROUP_CUSTOMER",
  SETTING_GROUP_RETAILER: "SETTING_GROUP_RETAILER",
  MANAGE_PERSONEL: "MANGE_PERSONEL",
  MANAGE_PROGRAM: "MANGE_PROGRAM",
  MANAGE_REPORT: "MANGE_REPORT",
  MANAGE_SETTING: "MANGE_SETTING",
  MANAGE_OPERATOR: "MANGER_OPERATOR",
  MAIN_TITLE: "MAIN_TITLE",
  MANAGE_TITLE: "MANAGE_TITLE",
  REPORT_TITLE: "REPORT_TITLE",
  SETTING_TITLE: "SETTING_TITLE",
  MANAGE_WAREHOUSE: "MANAGE_WAREHOUSE",
  WARE_HOUSE_MANAGE_EXPORT: "WARE_HOUSE_MANAGE_EXPORT",
  WARE_HOUSE_MANAGE_IMPORT: "WARE_HOUSE_MANAGE_IMPORT",
  SEARCH_WAREHOUSE_EXPORT: "SEARCH_WAREHOUSE_EXPORT",
  SEARCH_WAREHOUSE_IMPORT: "SEARCH_WAREHOUSE_IMPORT",
};

export const MENUITEMS = [
  {
    menutitle: "MAIN",
    key: MENU_KEY.MAIN_TITLE,
  },
  {
    path: `${import.meta.env.BASE_URL}dashboards`,
    title: "Dashboard",
    icon: icon1,
    // badgetxt: badge1,
    type: "link",
    active: false,
    selected: false,
    key: MENU_KEY.DASHBOARD,
  },
  {
    menutitle: "Quản lý",
    key: MENU_KEY.MAIN_TITLE,
  },
  {
    path: `${import.meta.env.BASE_URL}accounts`,
    title: "Tài khoản",
    icon: icon6,
    // badgetxt: badge1,
    type: "link",
    active: false,
    selected: false,
    key: MENU_KEY.ACCOUNTS,
  },
  {
    title: "Tổng đài viên",
    icon: icon5,
    badgetxt: "",
    type: "sub",
    active: true,
    selected: false,
    dirchange: false,
    key: MENU_KEY.MANAGE_OPERATOR,
    children: [
      // {
      //   path: `${import.meta.env.BASE_URL}customer/agent`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false,
      //   title: "Giao dịch trong ngày",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}customer/farmer`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false,
      //   title: "Đầu số 80xx",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}customer/farmer`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false,
      //   title: "Tra cứu mã",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}customer/farmer`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false,
      //   title: "Tra cứu số điện thoại",
      // },
      // {
      //   path: `${import.meta.env.BASE_URL}customer/farmer`,
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   dirchange: false,
      //   title: "Tra cứu topup",
      // },
      {
        path: `${import.meta.env.BASE_URL}operator/search-product-code`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Tra cứu mã sản phẩm",
      },
    ],
  },
  {
    title: "Thông tin kho",
    icon: icon7,
    badgetxt: "",
    type: "sub",
    active: true,
    selected: false,
    dirchange: false,
    key: MENU_KEY.MANAGE_WAREHOUSE,
    children: [
      {
        path: `${
          import.meta.env.BASE_URL
        }warehouse/export/search-warehouse-export`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Tra cứu thông tin xuất kho",
      },

      {
        path: `${
          import.meta.env.BASE_URL
        }warehouse/import/search-warehouse-import`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Tra cứu thông tin nhập kho",
      },
      {
        path: `${import.meta.env.BASE_URL}warehouse/export`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Danh sách xuất kho",
      },
      {
        path: `${import.meta.env.BASE_URL}warehouse/import`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Danh sách nhập kho",
      },
    ],
  },
  {
    title: "Khách hàng",
    icon: icon4,
    badgetxt: "",
    type: "sub",
    active: true,
    selected: false,
    dirchange: false,
    key: MENU_KEY.CUSTOMERS,
    children: [
      {
        path: `${import.meta.env.BASE_URL}customer/validate`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Đã xác thực",
      },
      {
        path: `${import.meta.env.BASE_URL}customer/unvalidate`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Chờ xác thực",
      },
    ],
  },
  {
    title: "Nhân sự",
    icon: icon16,
    type: "sub",
    path: `${import.meta.env.BASE_URL}employee`,
    active: false,
    key: MENU_KEY.MANAGE_PERSONEL,
    children: [
      {
        path: `${import.meta.env.BASE_URL}employee`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Thông tin nhân sự",
        key: MENU_KEY.EMPLOYEES,
      },
      {
        path: `${import.meta.env.BASE_URL}employee/role`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Quản lý cấp bậc",
        key: MENU_KEY.ROLES,
      },
      {
        path: `${import.meta.env.BASE_URL}employee/department`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Quản lý bộ phận",
        key: MENU_KEY.DEPARTMENTS,
      },
    ],
  },
  {
    title: "Sản phẩm",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    icon: icon2,
    path: `${import.meta.env.BASE_URL}product`,
    key: MENU_KEY.PRODUCTS,
  },
  {
    title: "Chương trình",
    icon: icon17,
    badgetxt: "",
    type: "sub",
    active: true,
    selected: false,
    dirchange: false,
    key: MENU_KEY.MANAGE_PROGRAM,

    children: [
      {
        path: `${import.meta.env.BASE_URL}program/point`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Tích điểm",
        key: MENU_KEY.PROGRRAM_POINT,
      },
      {
        path: `${import.meta.env.BASE_URL}program/topup`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Topup",
        key: MENU_KEY.PROGRAM_TOPUP,
      },
    ],
  },
  {
    menutitle: "Báo cáo",
    key: MENU_KEY.REPORT_TITLE,
  },
  {
    path: `${import.meta.env.BASE_URL}report`,
    title: "Báo cáo",
    icon: icon18,
    type: "sub",
    active: false,
    selected: false,
    dirchange: false,
    key: MENU_KEY.MANAGE_REPORT,

    children: [
      {
        path: `${import.meta.env.BASE_URL}report/agent`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Đại lý",
        key: MENU_KEY.REPORT_AGENT,
      },
      {
        path: `${import.meta.env.BASE_URL}report/farmer`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Nông dân",
        key: MENU_KEY.REPORT_FARMER,
      },
      {
        path: `${import.meta.env.BASE_URL}report/iQr`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "iQr",
        key: MENU_KEY.REPORT_IQR,
      },
      {
        path: `${import.meta.env.BASE_URL}report/program-point`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Chương trình tích điểm",
        key: MENU_KEY.PROGRRAM_POINT,
      },
      {
        path: `${import.meta.env.BASE_URL}report/topup`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Chương trình topup",
        key: MENU_KEY.PROGRAM_TOPUP,
      },
    ],
  },
  {
    menutitle: "Cài đặt",
    key: MENU_KEY.SETTING_TITLE,
  },
  {
    title: "Cài đặt",
    type: "sub",
    active: false,
    selected: false,
    dirchange: false,
    icon: icon3,
    key: MENU_KEY.MANAGE_SETTING,

    children: [
      {
        path: `${import.meta.env.BASE_URL}setting/area`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Phân vùng",
        key: MENU_KEY.SETTING_AREA,
      },
      {
        path: `${import.meta.env.BASE_URL}setting/group-customer`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Nhóm khách hàng",
        key: MENU_KEY.SETTING_GROUP_CUSTOMER,
      },
      {
        path: `${import.meta.env.BASE_URL}setting/group-retailer`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Nhóm đại lý",
        key: MENU_KEY.SETTING_GROUP_RETAILER,
      },
    ],
  },
];
